# Generated by Django 2.0 on 2018-03-17 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='authenticated',
            field=models.CharField(max_length=1),
        ),
    ]
