# Generated by Django 2.0 on 2018-03-17 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20180317_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='authenticated',
            field=models.BooleanField(default=False),
        ),
    ]
