# Generated by Django 2.0 on 2018-03-19 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20180317_2332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_rooms', models.IntegerField()),
                ('category', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('purpose', models.CharField(blank=True, max_length=50)),
                ('doarrival', models.DateTimeField()),
                ('dodeparture', models.DateTimeField()),
                ('dobooking', models.DateTimeField()),
                ('room_type', models.CharField(choices=[('ACS', 'AC Single'), ('NACS', 'Non AC Single'), ('ACD', 'AC Double'), ('NACD', 'Non AC Double')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='GuestHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('PhNo', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('SIN', 'Single'), ('DOB', 'Double'), ('ACS', 'AC Single'), ('NACS', 'Non AC Single'), ('ACD', 'AC Double'), ('NACD', 'Non AC Double'), ('SUIT', 'Suit')], max_length=4)),
                ('no_available', models.IntegerField()),
                ('gID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.GuestHouse')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovedBookings',
            fields=[
                ('booking_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mainapp.Bookings')),
            ],
        ),
        migrations.CreateModel(
            name='DisapprovedBookings',
            fields=[
                ('booking_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mainapp.Bookings')),
                ('reason', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='bookings',
            name='booker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.UserProfile'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='guestHouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.GuestHouse'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='guests',
            field=models.ManyToManyField(null=True, to='mainapp.Guest'),
        ),
    ]
